### ISSUE TITLE
How to install on Exim?

### ISSUE THREAD

**Issue by rickhessmann** [AbuseIO/AbuseIO#223]
I couldn't find any info about how to do it on an Exim system.
Not sure if the Postfix instructions are usable in any way.

Any help is appreciated.

**Comment by sndrsmnk** [comment]
The basic principles shown for Postfix do apply to setting this up with Exim.

You need to `route` messages addressed to a specific destination (or specific destinations), and `transport` it through a `pipe` which drives a PHP-script which needs to run as the user your AbuseIO install is using.

A very simplistic `router` which will match only on emails going to `notifier`@`isp.local` would look like this:

```
begin routers
# [ .. ]
abuseio_router:
    driver = accept
    domains = isp.local
    local_parts = notifier
    transport = abuseio_transport
    no_verify
```

It `accept`s and `transport`s the message to the `abuseio_transport` shown here:

```
begin transports
# [ .. ]
abuseio_transport:
    driver = pipe
    command = "/usr/bin/php -q /opt/abuseio/artisan --env=production email:receive"
    user = abuseio
    group = abuseio
    return_output
```

This in turn `pipe`s the message through the specified `command`, which will run as the `user` and `group` specified.

When placing that router, do mind the position you put it in. If you just stick it at the end of your existing routers, it might never run because routers are evaluated in a top-down process and the first one that handles a message (might) stop the process.

Exim provides *excellent* debugging though, so once the config has been placed, try and interpret the output of: `exim4 -d+route -bt notifier@isp.local` to see what happens!
