### ISSUE TITLE
Abuse.IO 4.1 Automatic Notifications using findcontact-custom

### ISSUE THREAD

**Issue by justcfx2u** [AbuseIO/AbuseIO#228]
I am using external lookups with Abuse.IO 4.1 through findcontact-custom.

In the previous version, Abuse.IO 4.0, I was able to set `$contact->auto_notify = true;` and notifications would send.

This no longer works for Abuse.IO 4.1 because of the new notification system.

Whenever I visit a ticket (in the web interface) that was populated using findcontact-custom, the "Notification" field is always "Manual".

In order to get notifications sent automatically seems to require the use of the `contact_notification_methods` table, which in turn requires a local Abuse.IO Contact (an entry in the `contacts` table).

In findcontact-custom I am able to do `$contact->save()` and then `$contact->addNotificationMethod(['method'=> 'Mail']);` and `$contact->save()` again, but I consider this a workaround since it will begin duplicating my external contact database into Abuse.IO itself.

I would like to see a way for notifications methods to be stored with the ticket (much as `ip_contact_name` and `ip_contact_email` are already recorded). This will prevent duplication of the contact database. However, this may cause issues when trying to use multiple `findcontact-*` modules at the same time.

> 17:55 < cfx__> it's my understanding that findcontact-custom does not persist contacts in the database, so a contact's data is only copied to the ticket (ip_contact_account_id, ip_contact_reference, ip_contact_name, ip_contact_email, ip_contact_api_host)
> 17:56 < cfx__> and then when notification job comes around, it has no entries in contact_notification_methods for a non-persisted contact
> 17:56 < jover> indeed
> 17:56 < cfx__> I suppose I could try saving everything, but duplicating a contacts database seems bad
> 17:57 < jover> looks like a thinko :)
> 17:57 < jover> looks like we need to add that info to the ticket
> 17:57 < cfx__> that would be wonderful :)
> 17:58 < cfx__> that way notifications can be controlled by advanced lookup logic in findcontact-custom
> 17:58 < jover> ip_contact_methods and domain_contact_methods and modify the notifier to use them instead of looking them up in the contact
> 17:59 < jover> so the findcontact can specify which notification will be used
> 18:00 < cfx__> aye!
> 18:00 < jover> hmm could be a config hell
> 18:01 < jover> a misconfigurations of a findcontact-custom could be dangerous :)
> 18:01 < jover> when you have multiple findcontacts :)
> 18:01 < cfx__> ew, I didn't think of that
> 18:02 < cfx__> this is a showstopper for us, can't go forward with the project unless auto notification is resolved in findcontact-
> 18:02 < jover> multiple findcontacts work by a first-come-first-served method
> 18:03 < jover> this should be working, not just in your case :)
> 18:03 < jover> you can add it as a bug

**Comment by devaqto** [comment]
I am quite surprised that this issue is still open an unresolved. How are people using AbuseIO without a working notification system?
@justcfx2u did you find a way to keep the Contacts database of AbuseIO empty? Because we fetch this data from our portal and we would like to keep it clean.

@kruisdraad how did you do this at BIT?

**Comment by kruisdraad** [comment]
You are assuming it doesnt work for others, based on your own use case? We have loads of requests and priorities and keep in mind that we are all volunteers with not a lot of free time. You are free to submit a PR to solve this issue.

find-contact-external is a boiler plate, a rough example where developers can create their own code to implement find-contact. We cannot build a one-size-fits-all code, as there are simply soo many unique cases with implementations.

That said, i read the code changes on this. I dont know why the other devs broken this without backwards compatibility, but the code is still intact, the auto_notify flag is still passed from the contact into the ticket ... and the auto_notify from the ticket is still used for noticiations. The flag has been removed from the model and changed into a method. Looking at the code the tickets contact data is still used and not the contacts reference (as these could change)

I was not involved with this method so it will take me a lot of time to read into the code in-depth to see how to solve this, but you could merge your 4.0 requirement into 4.3 by removing the method and making it a boolean again and merge the original notification methodas the original code still uses these flags in the ticket.

Also using ->save() is not that bad of an idea, it would act as a caching layer for gui ... since it always save a save() it overwrites the local data so your portal is always leading data. It will cost you a little more storage for the contacts, but you win this back in some more speed in the backend.
