### ISSUE TITLE
Being spammed by failing process

### ISSUE THREAD

**Issue by webtel** [AbuseIO/AbuseIO#321]
Hi

Getting thousands of these emails in the admin Mailbox. How to solve ?

Alert: There are 2 jobs that have failed:

2 database abuseio_collector {"job":"Illuminate\\Queue\\CallQueuedHandler@call","data":{"command":"O:29:\"AbuseIO\\Jobs\\CollectorProcess\":4:{s:9:\"collector\";s:4:\"Snds\";s:9:\"queueName\";s:17:\"abuseio_collector\";s:5:\"queue\";N;s:5:\"delay\";N;}"}} 2019-02-26 15:00:18
1 database abuseio_collector {"job":"Illuminate\\Queue\\CallQueuedHandler@call","data":{"command":"O:29:\"AbuseIO\\Jobs\\CollectorProcess\":4:{s:9:\"collector\";s:4:\"Snds\";s:9:\"queueName\";s:17:\"abuseio_collector\";s:5:\"queue\";N;s:5:\"delay\";N;}"}} 2019-02-26 15:00:18

**Comment by kruisdraad** [comment]
in the database you can get the full data from this job. It looks like one of your collectors is failing. Most common errors are enabling a collector without configuring it, e.d. enabled SNDS without API key or added RBLDNS without configuring scanned ranges, etc.

The collector itself should log (syslog) on this matter, so try grepping on 'collector' in the logs.

**Comment by sndrsmnk** [comment]
There's much to be gained here. I thought of opening a new ticket, but this ticket seems related.

I'm getting a couple of seemingly spurious failed jobs per day, too, all in the `abuseio_email_incoming` queue:
```
| 24 | database   | abuseio_email_incoming | AbuseIO\Jobs\EmailProcess | 2019-05-08 05:43:19 |
```
For which i have to go in the db, or wait for the automated mail, to see more information that doesn't tell me anything at all, really, you'd have to be a core dev to understand this:
```
| 24 | database   | abuseio_email_incoming | {"job":"Illuminate\Queue\CallQueuedHandler@call","data":{"command":"O:25:"\AbuseIO\Jobs\EmailProcess":4:{s:8:"filename";s:61:"mailarchive/20190508/a26b6a18-c297-4f9a-8886-9b6b605a303d.eml";s:9:"queueName";s:22:"abuseio_email_incoming";s:5:"queue";N;s:5:"delay";N;}"}} | 2019-05-08 05:43:19 |
```
I'd expect the timestamp, `2019-05-08 05:43:19` to match with AbuseIO logs in my syslog, but there's nothing indicating failure at that time in my logs. If i grep for that eml filename, i see that message in my logs at `2019-05-08 07:40:24` which is completely different from the timestamp in the failed queue.

The message then appears not to have been processed with errors, it was a HUGE report though:
```
abuseio[23274]: production.INFO: AbuseIO\Parsers\Shadowserver: : Parser completed with 0 warnings and collected 343 incidents to save
abuseio[23274]: production.INFO: AbuseIO\Jobs\IncidentsValidate: Validator has ended without errors
```
Followed by a (very!) long sequence of our custom `getContactBy*` module invocations, and it is there where i find that the `findcontact` module caused a framework error because of an unhandled '500 Internal Server Error' reported by an external source.

Ideas:
* Separate the `findcontact` / `getContactBy*` invocations from the actual accepting/parsing of a report.
* Fix the logged timestamps to match system time.
* Propagate errors better / improve the mesasge in the `failed_jobs` table.
* Provide ways to investigate failed jobs w/o going in the MySQL CLI.

**Comment by kruisdraad** [comment]
@1 findcontact is a specific part in a chain of events. you should always do a try->catch and capture errors. If you return 'false' it would fall back onto the default 'UNDEF'. But it cannot get passed framework errors if the developer forgets to handle these errors. We could try to wrap met method in a try/catch from the parent safegaurding it.

@2 the job list doenst show it (listing if from laravel itself, not abuseio so hard to chance, but there is a UUID in the job. This UUID matches your logs, you'd just need to know where to look. Its better to have this UUID then time as multiple jobs could fail on the same time.

@3/4 yes preferable we should store the logs linked to a job (with the UUID) so its easier to view why it has failed.

@5 the reason for having the initial contact correct is for aggregation. If another ticket is added as UNDEF first, it will never aggregate. Therefor its a choice . e.g.:
ignore it, resulting in duplicate tickets with different events, which at this time you cannot merge, updating the contact will create a aggregation error for the future events, which sucks
handle it, but NOT going undef but fail the job. This way you can fix the issue and retry the jobs the normal way, without the need for updating.
queue it, using a message bus to transport each event along the way splitting 1 large job into many small jobs. Which is more efficiënt anyways and gives you abetter view WHER Ein the process it got stuck for each event.

/50c/
